spring:
  config:
    activate:
      on-profile: local
    import:
    - optional:classpath:application-jwt.yml
    - optional:file:.env[.properties]
  application:
    name: zlzone-delivery

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: sa
    password: sa

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    hibernate:
      query:
        in_clause_parameter_padding: true
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
